n = int(input('Qual o número você deseja ver sua tabuaba: '))
print('A tabuada de multiplicação do número {} é'.format(n))
print('{}*1={}'.format(n, n*1))
print('{}*2={}'.format(n, n*2))
print('{}*3={}'.format(n, n*3))
print('{}*4={}'.format(n, n*4))
print('{}*5={}'.format(n, n*5))
print('{}*6={}'.format(n, n*6))
print('{}*7={}'.format(n, n*7))
print('{}*8={}'.format(n, n*8))
print('{}*9={}'.format(n, n*9))
print('{}*10={}'.format(n, n*10))
print('A tabuada de divisão do número {} é'.format(n))
print('{}÷1={:.2f}'.format(n, n/1))
print('{}÷2={:.2f}'.format(n, n/2))
print('{}÷3={:.2f}'.format(n, n/3))
print('{}÷4={:.2f}'.format(n, n/4))
print('{}÷5={:.2f}'.format(n, n/5))
print('{}÷6={:.2f}'.format(n, n/6))
print('{}÷7={:.2f}'.format(n, n/7))
print('{}÷8={:.2f}'.format(n, n/8))
print('{}÷9={:.2f}'.format(n, n/9))
print('{}÷10={:.2f}'.format(n, n/10))
print('A tabuada de adição do número {} é'.format(n))
print('{}+1={}'.format(n, n+1))
print('{}+2={}'.format(n, n+2))
print('{}+3={}'.format(n, n+3))
print('{}+4={}'.format(n, n+4))
print('{}+5={}'.format(n, n+5))
print('{}+6={}'.format(n, n+6))
print('{}+7={}'.format(n, n+7))
print('{}+8={}'.format(n, n+8))
print('{}+9={}'.format(n, n+9))
print('{}+10={}'.format(n, n+10))
print('A tabuada de subtração do número {} é'.format(n))
print('{}-1={}'.format(n, n-1))
print('{}-2={}'.format(n, n-2))
print('{}-3={}'.format(n, n-3))
print('{}-4={}'.format(n, n-4))
print('{}-5={}'.format(n, n-5))
print('{}-6={}'.format(n, n-6))
print('{}-7={}'.format(n, n-7))
print('{}-8={}'.format(n, n-8))
print('{}-9={}'.format(n, n-9))
print('{}-10={}'.format(n, n-10))
